AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Lambda function for contact page reception and S3 bucket for hosting React application

Globals:
  Function:
    Timeout: 3
    MemorySize: 128

Resources:
  ContactReceiverFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: contact/
      Handler: app.handler
      Runtime: nodejs14.x
      Events:
        ContactApi:
          Type: HttpApi
          Properties:
            Path: /contact
            Method: post
            PayloadFormatVersion: '2.0'
        OptionsApi:
          Type: HttpApi
          Properties:
            Path: /contact
            Method: options
            PayloadFormatVersion: '2.0'

  ContactApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      CorsConfiguration:
        AllowMethods:
          - POST
          - OPTIONS
        AllowHeaders:
          - Content-Type
        AllowOrigins:
          - "*"
  
  # Added Resources for S3 Hosting
  ReactAppBucket:
    Type: AWS::S3::Bucket
    Properties:
      PublicAccessBlockConfiguration:
          BlockPublicPolicy: false
          RestrictPublicBuckets: false
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: index.html
        
  ReactAppBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal: "*"
            Action:
              - s3:GetObject
            Resource: !Sub "arn:aws:s3:::${ReactAppBucket}/*"
      Bucket: !Ref ReactAppBucket

Outputs:
  ApiEndpoint:
    Description: "The API endpoint URL"
    Value: !Sub "https://${ContactApi}.execute-api.${AWS::Region}.amazonaws.com/prod"
  WebsiteURL:
    Description: "URL of the website"
    Value: !Sub "http://${ReactAppBucket}.s3-website-${AWS::Region}.amazonaws.com"
  BucketName:
    Description: "Name of the S3 bucket hosting the React app"
    Value: !Ref ReactAppBucket