AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Lambda function for contact page reception

Globals:
  Function:
    Timeout: 3
    MemorySize: 128

Resources:
  ContactReceiverFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: contact/
      Handler: app.handler
      Runtime: nodejs14.x
      Events:
        ContactApi:
          Type: HttpApi
          Properties:
            Path: /contact
            Method: post
            PayloadFormatVersion: '2.0'
        OptionsApi:
          Type: HttpApi
          Properties:
            Path: /contact
            Method: options
            PayloadFormatVersion: '2.0'

  ContactApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      CorsConfiguration:
        AllowMethods:
          - POST
          - OPTIONS
        AllowHeaders:
          - Content-Type
        AllowOrigins:
          - "*"

Outputs:
  ApiEndpoint:
    Description: "The API endpoint URL"
    Value: !Sub "https://${ContactApi}.execute-api.${AWS::Region}.amazonaws.com/prod"
